import {
  ATTACK_MODE_ANALYST_FRAMEWORK,
  PLUSULTRA_APP_OPS,
} from "@/lib/analyst-framework";

/** @deprecated Use ATTACK_MODE_ANALYST_FRAMEWORK + PLUSULTRA_APP_OPS in context-formatter. */
export const PLUSULTRA_APP_BRIEFING = `${ATTACK_MODE_ANALYST_FRAMEWORK}

---

${PLUSULTRA_APP_OPS}`;

export { ATTACK_MODE_ANALYST_FRAMEWORK, PLUSULTRA_APP_OPS };
